name: STX3_test
channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - dill
  - h5py
  - python=3.8
  - jupyterlab
  - matplotlib
  - numpy>=1.19
  - numba>=0.43.1
  - pandas
  - pip
  - scikit-learn
  - scipy>=1.6
  - sqlite
  - statsmodels
  - pingouin
  - pip:
      - "--editable=/home/mplitt/repos/TwoPUtils/"
      - "--editable=/home/mplitt/repos/suite2p/"
      - -e .
