name: STX3_test
channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - dill>=0.3
  - h5py>=2.10.0
  - python=3.8
  - jupyter
  - jupyterlab
  - matplotlib
  - numba
  - numpy>=1.16
  - numba>=0.43.1
  - pandas
  - pip
  - scikit-learn
  - scipy
  - sqlite=3.33.0
  - statsmodels
  - mkl_fft=1.0.10
  - mkl=2019.3
  - pip:
      - "--editable=git+https://github.com/GiocomoLab/TwoPUtils"
      - -e .