

KO_sessions = {'4467975.1': (({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                              {'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 6, 'scan': 14}),
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             ({'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 10}),
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             ({'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5}),
                             ),

               '4467975.2': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 3, 'scan': 8},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 9},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                             ({'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5}),
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             ({'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8}),
                             ),

               '4467975.3': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 7},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 7},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                             ({'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 6},),
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             ({'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},),
                             ),

               '4467975.4': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             ({'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},),
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             ({'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},),
                             ),

               '4467975.5': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 7},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                             ({'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 8},),
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             ({'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 9},),
                             ),

               }

KO_sessions_ravel = KO_sessions = {'4467975.1': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                              {'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 6, 'scan': 14},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 10},
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             {'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                             ),

               '4467975.2': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 3, 'scan': 8},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 9},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                             {'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             {'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                             ),

               '4467975.3': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 7},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 7},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                             {'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 6},
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             {'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                             ),

               '4467975.4': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                              {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             {'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                              {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                             ),

               '4467975.5': ({'date': '28_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '29_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '30_09_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                             {'date': '01_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 7},
                             {'date': '02_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                             {'date': '03_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                             {'date': '04_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                             {'date': '04_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 8},
                             {'date': '05_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                             {'date': '06_10_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                             {'date': '06_10_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 9},
                             ),

               }

CTRL_sessions = {'4467331.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 7},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                               ({'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                                {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},),
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 1},
                               ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5}),
                               ),

                 '4467331.2': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               ({'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                                {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 12},),
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               ({'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                                {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},),
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                               ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4}),
                               ),

                 '4467332.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                               ({'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                                {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},),
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 1},
                               ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5}),
                               ),

                 '4467332.2': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 14},
                               {'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 18},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 3, 'scan': 9},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               ({'date': '06_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                                {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 6},),
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 2},
                               ({'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6}),
                               ),

                 '4467333.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 4},
                               {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                               ({'date': '06_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                                {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},),
                               {'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                               ({'date': '08_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '08_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4}),
                               ),

                 }


CTRL_sessions_ravel = {'4467331.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 7},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                               {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                                {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 1},
                               {'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 3},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                               ),

                 '4467331.2': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                                {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 12},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                                {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 4},
                               {'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               ),

                 '4467332.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 8},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                               {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                                {'date': '05_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 1},
                               {'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 5},
                               ),

                 '4467332.2': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 14},
                               {'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 18},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 3, 'scan': 9},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '04_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                               {'date': '06_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 3},
                                {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 6},
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 2, 'scan': 2},
                               {'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '07_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                               ),

                 '4467333.1': ({'date': '29_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '30_11_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 6},
                               {'date': '01_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '02_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               {'date': '03_12_2020', 'scene': 'YMaze_LNovel', 'session': 2, 'scan': 4},
                               {'date': '05_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                               {'date': '06_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 2},
                               {'date': '06_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 5},
                               {'date': '07_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                               {'date': '08_12_2020', 'scene': 'YMaze_RewardReversal', 'session': 1, 'scan': 2},
                                {'date': '08_12_2020', 'scene': 'YMaze_LNovel', 'session': 1, 'scan': 4},
                               ),

                 }
